### ISSUE TITLE
Fix structure field access subscripts

### ISSUE THREAD

**Issue by Override-6** [moshell-lang/moshell#167]
Current parser struggles when parsing a subscript over a field access (`$obj.field[0]`).
This is caused because the parser conflicts with the parsing of a method call with type parameters.
The easy way to get rid of this would to simply do a big lookahead to find if there is a `(` after the argument list, but this wont support tupple types: `$obj.map[(0, 1)] (if we ever add them). This would also be too greedy.

**Comment by syldium** [comment]
This would also deny using a vector of callables directly:
```kt
val v: Vec[() -> Unit] = ...
$v[0]() // 0 is not a valid parameter type...
```

Those two syntaxes conflicts and need to be distinguishable. There are two ways:
- Use a turbo-fish operator to declare type parameters and isolate them for the name. `.identifier::[T]()` is a parameterized method call, `.identifier[T]()` is an indexing operation followed by a call.
- Change how type parameters are declared, for instance with `<T>` instead of `[T]`. This introduces a look ahead for the nearest parenthesis, since the `<`  token is also used for redirections.
