### ISSUE TITLE
Continue to report errors once one was found in an expression

### ISSUE THREAD

**Issue by Override-6** [moshell-lang/moshell#46]
The current parser is able to report multiple errors per files, but can't report multiple errors per _statements_.

**Comment by Override-6** [comment]
Maybe we should create a `display` create that'll be in charge of displaying all errors and warns that can be emitted by parser and analyzer ? This way in parser we would only pass a `FailDisplayer` that'll be in charge of displaying errors and warns.

**Comment by Override-6** [comment]
I think that the fact that the parser returns all the errors it may have encountered in a ParserReport structure is a good idea but this pattern prevents us from generating several errors while keeping the internal code clean

**Comment by Override-6** [comment]
In tests we'd still be able to test the reported errors using a specific implementation of `FailReporter` : 
```rs
#[test]
fn test_example() {
    let report = RetainFailReporter::new()
    let ast = parse(Source::unknown("<erroneous_input>"))
    assert_eq(ast, Expr::Error)
    assert_eq(report.errors, vec![ReportError {
           message: "some message",
           location: <range>
           kind: Unexpected
    }])
}
```

**Comment by syldium** [comment]
The `context` crate where all the sources and the display types should be. All those intermediary crates like `lexer` and `parser` should not depend on any standard error output. It's the job of the consumer of those crates to display the errors, format them or not.

On the public API side, a diagnostic consumer, that you call `FailReporter`, could be an idea if passed to the `parse` function. The main drawback I think of is that it allows the user to skip the errors without explicitly asking to do so (`expect(msg)` or `unwrap()`). In my opinion, having a `ParseReport` ensures the user is aware that parsing is a fallible operation, that can be quickly `.except`ed.
On the implementation side, having a `Expr::Error` degrades the type quality of `Expr` since it will be easy to miss a function that return an error. The `?` operation cannot yet be implemented for custom types (https://doc.rust-lang.org/std/ops/trait.Try.html).

**Comment by Override-6** [comment]
Why do you want to force the "user" (which is ourself here) not to skip errors, if the caller of the `parse` method does not want to report errors, you can't force him to do so, returning a ParseReport would lead to the same issue. (the FailReporter parameter is explicit enough to tell the caller that errors will end up here)
I think that the parse method should not be considered as a faillible operation, because a syntacting mistakes are intended, moreover the parser is designed to recover after each error so it's weird to consider that the parse method failed when it was able to recover multiple times. those errors are not real failures that made the parser not able to accomplish its task.
 
The `FailReporter` would be a trait, so the parser would not depend on any standard output as the outputs would be handled behind the abstraction

**Comment by Override-6** [comment]
The use of `Expr::Error` would be to better mark expressions that could not be parsed, sorry i was not precise enough about its use case : 

```kt
fun errors(x, y, z) = {
    fun //error
    echo ) // error
    echo $x $y //OK
}
```
```rs
Function { 
   Block {
       Error, 
       Error, 
       Call {
          echo,
          $x,
          $y
       }
   }
}
```
